package com.nivaapp.niva

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import org.json.JSONObject

/**
 * "Send to Niva."
 *
 * The listener sees the notification shade; this sees everything else. A
 * WhatsApp message with a promise in it, an email with a due date, the text
 * of a screenshot — anything Android can share as text can be handed to
 * Niva from the share sheet, and it goes in at the same door an SMS does:
 * the signal queue, then the normaliser, the engine, the validator, the
 * spaces and the watches.
 *
 * Deliberately a separate, translucent activity rather than a change to
 * `MainActivity`. `MainActivity.kt` is generated by prebuild and owned by
 * Expo; this file is copied in by the config plugin next to the listener
 * service, so it survives `prebuild --clean` and never touches generated
 * code.
 *
 * After enqueueing it opens the app, so the person sees the card appear —
 * the foreground drain picks the signal up within a second. Nothing is
 * classified here; this activity stays as dumb as the listener.
 */
class NivaShareActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        try {
            val received = intent
            val isText = received?.action == Intent.ACTION_SEND && received.type?.startsWith("text/") == true
            val text = if (isText) received.getStringExtra(Intent.EXTRA_TEXT)?.trim() else null

            if (!text.isNullOrEmpty()) {
                val subject = received.getStringExtra(Intent.EXTRA_SUBJECT)?.trim()?.takeIf { it.isNotEmpty() }
                val signal = JSONObject().apply {
                    put("id", "share-${System.currentTimeMillis()}-${text.length}")
                    put("source", "notification")
                    put("packageName", "shared")
                    put("sender", subject ?: JSONObject.NULL)
                    put("title", subject ?: JSONObject.NULL)
                    put("text", text)
                    put("receivedAt", System.currentTimeMillis())
                }
                NivaSignalQueue.enqueue(applicationContext, signal)
                Toast.makeText(this, "Sent to Niva", Toast.LENGTH_SHORT).show()

                packageManager.getLaunchIntentForPackage(packageName)?.let { launch ->
                    launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
                    startActivity(launch)
                }
            } else {
                Toast.makeText(this, "Nothing to send", Toast.LENGTH_SHORT).show()
            }
        } catch (e: Throwable) {
            Log.e(TAG, "Failed to accept shared text", e)
        }
        finish()
    }

    private companion object {
        const val TAG = "NivaShare"
    }
}
